# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gist < Formula
  desc "Context intelligence for LLM applications — index everything, retrieve only what matters"
  homepage "https://github.com/sirerun/gist"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/gist/releases/download/v1.0.0/gist_1.0.0_darwin_amd64.tar.gz"
      sha256 "b51e521599393b42a30214036fbdcbd06bc9b6ccbb13c3834f516d828ed45e02"

      define_method(:install) do
        bin.install "gist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/gist/releases/download/v1.0.0/gist_1.0.0_darwin_arm64.tar.gz"
      sha256 "e9e433b20d41fd83299452862eb14fed3a04d562d64f0dc44796f0ba4483cd39"

      define_method(:install) do
        bin.install "gist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/gist/releases/download/v1.0.0/gist_1.0.0_linux_amd64.tar.gz"
      sha256 "ff08b6567fadd2bc002a77603b62809bfa486f007c80038d1abe475188b08c0d"
      define_method(:install) do
        bin.install "gist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/gist/releases/download/v1.0.0/gist_1.0.0_linux_arm64.tar.gz"
      sha256 "90cb2947355c3da1bc153e4e4636f4d436e18d72c6c2ee4323421e692e8d8e17"
      define_method(:install) do
        bin.install "gist"
      end
    end
  end

  test do
    system "#{bin}/gist", "version"
  end
end
