# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gist < Formula
  desc "Context intelligence for LLM applications — index everything, retrieve only what matters"
  homepage "https://github.com/sirerun/gist"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/gist/releases/download/v1.2.0/gist_1.2.0_darwin_amd64.tar.gz"
      sha256 "16d14a0278331388fef39465891ec2678234f123f1828678afb8078d69fc84d0"

      define_method(:install) do
        bin.install "gist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/gist/releases/download/v1.2.0/gist_1.2.0_darwin_arm64.tar.gz"
      sha256 "21d2ff72273114cbe648fdd394edf6249208e5d6405953f8ec402a3e3080b316"

      define_method(:install) do
        bin.install "gist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/gist/releases/download/v1.2.0/gist_1.2.0_linux_amd64.tar.gz"
      sha256 "e370c97a42d49d3ac71466d05d6e68643f5e901b38628b3896b5cc185bcdb43c"
      define_method(:install) do
        bin.install "gist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/gist/releases/download/v1.2.0/gist_1.2.0_linux_arm64.tar.gz"
      sha256 "be0483031140d7020760dc4c1fc36ea9c77c0e4d4ba44e00a1b74adc114b1eac"
      define_method(:install) do
        bin.install "gist"
      end
    end
  end

  test do
    system "#{bin}/gist", "version"
  end
end
