# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mint < Formula
  desc "Generate MCP servers from OpenAPI specs"
  homepage "https://github.com/sirerun/mint"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/mint/releases/download/v1.7.0/mint_1.7.0_darwin_amd64.tar.gz"
      sha256 "934d4a6742e34bc57a6f786aec6f9ede88a9a6b0d4272e1b2d63a7ff3f640310"

      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/mint/releases/download/v1.7.0/mint_1.7.0_darwin_arm64.tar.gz"
      sha256 "7892b089dfe6fa5869b5110b9e249bc450460ffc3dfbacb1a7632b0fd12dcc22"

      define_method(:install) do
        bin.install "mint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.0/mint_1.7.0_linux_amd64.tar.gz"
      sha256 "2be9be46b60e1aec3c072200b37041832aba5da53cdfc7d568ea1afdc4412caa"
      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.0/mint_1.7.0_linux_arm64.tar.gz"
      sha256 "3aa4b1ba5ee87e8ef297677adf7c95612c7443bc4fd32734004d96f50f67d49c"
      define_method(:install) do
        bin.install "mint"
      end
    end
  end
end
