# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mint < Formula
  desc "Generate MCP servers from OpenAPI specs"
  homepage "https://github.com/sirerun/mint"
  version "1.7.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/mint/releases/download/v1.7.3/mint_1.7.3_darwin_amd64.tar.gz"
      sha256 "db31938ec8f2cd0d77f0e59c76974155d9ab62aa4f4be4130be0adf1b6945284"

      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/mint/releases/download/v1.7.3/mint_1.7.3_darwin_arm64.tar.gz"
      sha256 "695bc03504a4aecc11a76e2dae1ba884d4e0ecee533a26aa36a7eeeff133cb11"

      define_method(:install) do
        bin.install "mint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.3/mint_1.7.3_linux_amd64.tar.gz"
      sha256 "3216a6b51d91af9e58716363c3f0985ca2ed9c4f9c17f180dc807da9f760b2b0"
      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.3/mint_1.7.3_linux_arm64.tar.gz"
      sha256 "47311b4ebcbf98a7ca2d7f61e775c8633bc20f3a4a759b427f6d0e1f81b49c29"
      define_method(:install) do
        bin.install "mint"
      end
    end
  end
end
