# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mint < Formula
  desc "Generate MCP servers from OpenAPI specs"
  homepage "https://github.com/sirerun/mint"
  version "1.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/mint/releases/download/v1.7.1/mint_1.7.1_darwin_amd64.tar.gz"
      sha256 "173351f1d825a1d9f669f00b228b228f062478e11776c28c968e4e261b8275df"

      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/mint/releases/download/v1.7.1/mint_1.7.1_darwin_arm64.tar.gz"
      sha256 "44ead73a3b74043efda5479fa43bae4f67b979727b30a9a3721c001166826e3b"

      define_method(:install) do
        bin.install "mint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.1/mint_1.7.1_linux_amd64.tar.gz"
      sha256 "7a8bfa992e75f2905784f6460dc85c8a16d1f186700ab9a56585c8262673e076"
      define_method(:install) do
        bin.install "mint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/mint/releases/download/v1.7.1/mint_1.7.1_linux_arm64.tar.gz"
      sha256 "15922072a00bb7a4c3038a96f383b841baa9f02b86075027391bf05c04ce4c0a"
      define_method(:install) do
        bin.install "mint"
      end
    end
  end
end
