# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saka < Formula
  desc "Free web search — no API keys, embeddable, MCP-ready"
  homepage "https://github.com/sirerun/saka"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_darwin_amd64.tar.gz"
      sha256 "9a4c937e91d4ea840b0a988c7dd60c2bb31093ecd941cc1e348ba82d2bc3f1ff"

      define_method(:install) do
        bin.install "saka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_darwin_arm64.tar.gz"
      sha256 "c22f949b5d790cfcd8587fc7d16859b7b35d0a8bdbc05128be52528d5c421149"

      define_method(:install) do
        bin.install "saka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_linux_amd64.tar.gz"
      sha256 "9fdaf7e7d06943a95b8d489ef6d508e829a7514ca096765143a4331b3668922a"
      define_method(:install) do
        bin.install "saka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_linux_arm64.tar.gz"
      sha256 "581ec324f19bc949c584aba58e5f9ea42a9442672bef3fd8f6c74b6c9ec21c24"
      define_method(:install) do
        bin.install "saka"
      end
    end
  end
end
