# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saka < Formula
  desc "Free web search — no API keys, embeddable, MCP-ready"
  homepage "https://github.com/sirerun/saka"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_darwin_amd64.tar.gz"
      sha256 "2cec22c21bf0cfafe35cae344b8e376082e9871c586f03f97bcb9bf2fc5852d8"

      define_method(:install) do
        bin.install "saka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_darwin_arm64.tar.gz"
      sha256 "f8a71944fd4d3a121b80cbdcc8b24468b3552bfd278d6833cfa9343870c6c8c4"

      define_method(:install) do
        bin.install "saka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_linux_amd64.tar.gz"
      sha256 "706f3d631799dee586019fcff16bdcec8b39d89c0a546e3cfff576f0f1245398"
      define_method(:install) do
        bin.install "saka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/saka/releases/download/v0.1.0/saka_0.1.0_linux_arm64.tar.gz"
      sha256 "389a20ca2f5d55912899a1c07be7b7ba0723f50c466aa33bca892c0104710315"
      define_method(:install) do
        bin.install "saka"
      end
    end
  end
end
