# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serenity < Formula
  desc "Claim-based personal memory and direction system"
  homepage "https://github.com/sirerun/serenity"
  version "0.1.9-hosted-candidate"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.9-hosted-candidate/serenity_0.1.9-hosted-candidate_darwin_arm64.tar.gz"
      sha256 "7f3bb42f765be66fe023ab3e6974571d493399c602002b28d2a68820f4fb4ecc"

      define_method(:install) do
        bin.install "serenity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.9-hosted-candidate/serenity_0.1.9-hosted-candidate_linux_amd64.tar.gz"
      sha256 "1321486c6d3c915b19232c0d7b64ddf8923951a47d3f57e58bab655d7b64461e"
      define_method(:install) do
        bin.install "serenity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.9-hosted-candidate/serenity_0.1.9-hosted-candidate_linux_arm64.tar.gz"
      sha256 "9643d4a81fcdef04f2f88ea41f6d95c0038fe374a1075c6c7bedc6632e570d6d"
      define_method(:install) do
        bin.install "serenity"
      end
    end
  end
end
