# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serenity < Formula
  desc "Claim-based personal memory and direction system"
  homepage "https://github.com/sirerun/serenity"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.1/serenity_0.1.1_darwin_arm64.tar.gz"
      sha256 "5694022dbdc2b96dd031f5435b821db5673cd69bb7a4717868812cc7d63f30ae"

      define_method(:install) do
        bin.install "serenity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.1/serenity_0.1.1_linux_amd64.tar.gz"
      sha256 "49bf57533c4678e3a337f8a9f7c8925588b8b7558056c48ee98a6f99f7b9796d"
      define_method(:install) do
        bin.install "serenity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirerun/serenity/releases/download/v0.1.1/serenity_0.1.1_linux_arm64.tar.gz"
      sha256 "78f967ee02abb6d8401ec10cf602209155f69a62b31106e4127963a538661669"
      define_method(:install) do
        bin.install "serenity"
      end
    end
  end
end
